spring:
  application:
    name: analyzer

  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry_analyzer
    username: postgres
    password: shareit
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

kafka:
  bootstrap-servers: localhost:9092

analyzer:
  kafka:
    consumer:
      hubs:
        group-id: analyzer-hub-events
        topic: telemetry.hubs.v1
      snapshots:
        group-id: analyzer-snapshot-events
        topic: telemetry.snapshots.v1

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext